controller_manager:
  ros__parameters:
    update_rate: 1000
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_controller:  
      type: position_controllers/JointGroupPositionController

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

position_controller:
  ros__parameters:
    joints:  
      - FrontLeftSteer_Joint  
      - FrontRightSteer_Joint  
    interface_name: position  
    command_interfaces:  
      - position  
    state_interfaces:  
      - position  
      - velocity  

velocity_controller:
  ros__parameters:
    joints:
      - FrontLeftWheel_Joint
      - FrontRightWheel_Joint
      - RearLeftWheel_Joint
      - RearRightWheel_Joint
      - LeftTrailer1_Joint
      - RightTrailer1_Joint
      - LeftTrailer2_Joint
      - RightTrailer2_Joint
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
